package com.example.network

import com.example.BuildConfig
import com.example.rag.RetrievedChunk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext

data class LlmResult(
    val text: String,
    val latencyMs: Long,
    val isSimulated: Boolean,
    val error: String? = null
)

class GeminiClient(
    private val apiService: GeminiApiService = GeminiApiService.create()
) {
    var customApiKey: String? = null

    val effectiveApiKey: String
        get() {
            val custom = customApiKey?.trim()
            if (!custom.isNullOrBlank()) return custom
            val buildKey = BuildConfig.GEMINI_API_KEY.trim()
            if (buildKey.isNotEmpty() && buildKey != "MY_GEMINI_API_KEY") return buildKey
            return ""
        }

    fun hasValidApiKey(): Boolean = effectiveApiKey.isNotBlank()

    suspend fun generateRagResponse(
        query: String,
        retrievedChunks: List<RetrievedChunk>
    ): LlmResult = withContext(Dispatchers.IO) {
        val startTime = System.currentTimeMillis()
        val apiKey = effectiveApiKey

        if (apiKey.isBlank()) {
            // Intelligent simulation showcasing RAG grounding
            delay(750) // Realistic processing delay
            val text = generateSimulatedRagResponse(query, retrievedChunks)
            return@withContext LlmResult(
                text = text,
                latencyMs = System.currentTimeMillis() - startTime,
                isSimulated = true
            )
        }

        try {
            val contextBuilder = StringBuilder()
            retrievedChunks.forEachIndexed { idx, chunk ->
                contextBuilder.append("--- SOURCE [${chunk.documentTitle} | Section ${chunk.chunkIndex}] ---\n")
                contextBuilder.append(chunk.text.trim())
                contextBuilder.append("\n\n")
            }

            val systemInstruction = Content(
                parts = listOf(
                    Part(
                        """
                        You are an expert enterprise AI assistant operating in RAG (Retrieval-Augmented Generation) mode.
                        Analyze the provided knowledge document snippets carefully and answer the user's question accurately.
                        
                        CRITICAL GUIDELINES:
                        1. Ground your answer strictly in the facts, specifications, numbers, and clauses stated in the provided context.
                        2. Explicitly cite the document title or section when stating facts (e.g. "[According to Apex-X Manual...]").
                        3. If the provided context does not contain sufficient information to answer the question, clearly state: "This information is not present in the provided knowledge base documents."
                        4. Do NOT speculate or invent facts beyond the retrieved passages.
                        """.trimIndent()
                    )
                )
            )

            val prompt = """
                DOCUMENT CONTEXT:
                $contextBuilder
                
                USER QUESTION:
                $query
                
                Please provide a direct, well-structured answer citing the specific document sources above.
            """.trimIndent()

            val request = GeminiRequest(
                contents = listOf(Content(parts = listOf(Part(prompt)))),
                systemInstruction = systemInstruction,
                generationConfig = GenerationConfig(temperature = 0.2f, maxOutputTokens = 1024)
            )

            val response = apiService.generateContent(apiKey, request)
            val answerText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: response.error?.message
                ?: "No response generated by model."

            LlmResult(
                text = answerText,
                latencyMs = System.currentTimeMillis() - startTime,
                isSimulated = false
            )
        } catch (e: Exception) {
            // Fallback to simulation with error note
            val fallback = generateSimulatedRagResponse(query, retrievedChunks)
            LlmResult(
                text = "$fallback\n\n*(Note: Live API request encountered: ${e.localizedMessage ?: "network issue"}. Displaying grounded local synthesis.)*",
                latencyMs = System.currentTimeMillis() - startTime,
                isSimulated = true,
                error = e.localizedMessage
            )
        }
    }

    suspend fun generateDirectResponse(query: String): LlmResult = withContext(Dispatchers.IO) {
        val startTime = System.currentTimeMillis()
        val apiKey = effectiveApiKey

        if (apiKey.isBlank()) {
            delay(550)
            val text = generateSimulatedDirectResponse(query)
            return@withContext LlmResult(
                text = text,
                latencyMs = System.currentTimeMillis() - startTime,
                isSimulated = true
            )
        }

        try {
            val systemInstruction = Content(
                parts = listOf(
                    Part(
                        "You are a helpful AI assistant. Answer the user's question to the best of your knowledge."
                    )
                )
            )

            val request = GeminiRequest(
                contents = listOf(Content(parts = listOf(Part(query)))),
                systemInstruction = systemInstruction,
                generationConfig = GenerationConfig(temperature = 0.7f, maxOutputTokens = 1024)
            )

            val response = apiService.generateContent(apiKey, request)
            val answerText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: response.error?.message
                ?: "No response generated by model."

            LlmResult(
                text = answerText,
                latencyMs = System.currentTimeMillis() - startTime,
                isSimulated = false
            )
        } catch (e: Exception) {
            val fallback = generateSimulatedDirectResponse(query)
            LlmResult(
                text = "$fallback\n\n*(Note: Live API request encountered: ${e.localizedMessage ?: "network issue"}. Displaying direct response baseline.)*",
                latencyMs = System.currentTimeMillis() - startTime,
                isSimulated = true,
                error = e.localizedMessage
            )
        }
    }

    private fun generateSimulatedRagResponse(query: String, chunks: List<RetrievedChunk>): String {
        if (chunks.isEmpty()) {
            return "Based on the available documents in the knowledge base, no relevant information was found to answer: \"$query\"."
        }

        val qLower = query.lowercase()

        return when {
            qLower.contains("warranty") || qLower.contains("drift") || qLower.contains("804") || qLower.contains("cryo") || qLower.contains("apex") || qLower.contains("helium") -> {
                """
                According to the **QuantumTech Apex-X (QX-900) Operations Manual**:
                
                • **Operating Temperature**: The CryoCore-4 active cooling operates at exactly **1.4 Kelvin** (with automatic protective shutdown above 2.1 K).
                • **Coolant Cycle**: Liquid Helium-3 replenishment is required on a strict **90-day cycle** performed only by Level-4 certified cryogenic technicians.
                • **Warranty Coverage & Clause 14.b**: Error code **ERR-804** signifies Sub-Kelvin Thermal Drift caused by vacuum seal degradation. Under SLA Clause 14.b, an emergency hardware replacement chassis is dispatched within **4 hours** when filed via the Q-Direct portal.
                • **Void Clause**: The use of water-based sprinkler systems instantly voids all warranty coverage; only Halon-5 gas extinguishing is authorized.
                """.trimIndent()
            }

            qLower.contains("per-diem") || qLower.contains("travel") || qLower.contains("flight") || qLower.contains("stipend") || qLower.contains("novacorp") || qLower.contains("remote") -> {
                """
                According to the **NovaCorp Enterprise Remote Work & Travel Policy (FY26)**:
                
                • **Per-Diem Rates**: Daily meal & incidental per-diem is capped at **$85 USD** in Tier-1 cities (San Francisco, NYC, London, Tokyo, Zurich) and **$65 USD** in Tier-2 locations. Single expenses over $25 USD require itemized receipts.
                • **Flight Booking Lead Time**: Domestic flights must be booked at least **14 days in advance** via Concur; international flights require at least **28 days advance notice** with VP sign-off.
                • **Home Office Stipend**: Eligible remote employees receive **$1,200 USD** once every **3 calendar years** under General Ledger code **EXP-9421**. Claims submitted inside the 3-year lockout period are automatically rejected.
                • **Work Abroad**: Permitted up to **20 business days** per fiscal year with 30 days advance approval from Corporate Security and People Ops.
                """.trimIndent()
            }

            qLower.contains("drone") || qLower.contains("vanguard") || qLower.contains("wind") || qLower.contains("altitude") || qLower.contains("beacon") || qLower.contains("battery") -> {
                """
                According to the **AeroDrone Vanguard-7 Operational Guide & Regulations**:
                
                • **Operational Limits**: Maximum legal altitude is **120 meters AGL** under CAD-88 directives. Maximum sustained operational wind speed is **38 km/h**; missions must immediately abort (RTH) if wind gusts exceed **42 km/h**.
                • **Failsafe & Emergency Frequency**: If telemetry is severed for over **15 seconds**, FailSafe-Alpha deploys a ballistic recovery parachute and broadcasts on emergency beacon frequency **406.025 MHz**.
                • **Battery Decommissioning**: Dual PX-700 LiPo battery packs must be retired after **250 recharge cycles** or if internal cell impedance exceeds **18 milliohms** at 20°C.
                """.trimIndent()
            }

            else -> {
                val primary = chunks.first()
                """
                Based on **${primary.documentTitle}** (Section ${primary.chunkIndex}):
                
                ${primary.text.trim()}
                
                *(Confidence: ${(primary.score * 100).toInt()}% match based on terms: ${primary.matchedTerms.joinToString(", ")})*
                """.trimIndent()
            }
        }
    }

    private fun generateSimulatedDirectResponse(query: String): String {
        val qLower = query.lowercase()

        return when {
            qLower.contains("warranty") || qLower.contains("drift") || qLower.contains("804") || qLower.contains("cryo") || qLower.contains("apex") || qLower.contains("helium") -> {
                """
                Generally, enterprise quantum computing systems require specialized cooling, typically utilizing liquid nitrogen or closed-cycle dilution refrigerators operating near absolute zero. 
                
                For hardware warranties, most enterprise server manufacturers offer standard next-business-day or 24/7 on-site support depending on your purchased enterprise service contract. Specific error codes such as thermal drift or coolant replenishment timelines vary widely between vendors (e.g., IBM, Rigetti, or D-Wave). You would need to check your specific vendor contract or contact customer support for warranty claim procedures and acceptable fire suppression standards.
                """.trimIndent()
            }

            qLower.contains("per-diem") || qLower.contains("travel") || qLower.contains("flight") || qLower.contains("stipend") || qLower.contains("novacorp") || qLower.contains("remote") -> {
                """
                Most corporate travel policies provide per-diem allowances based on GSA or local government standard rates, typically ranging between $50 and $100 per day depending on the cost of living of the destination city. 
                
                Flight bookings are usually recommended 2 to 3 weeks in advance through corporate booking tools like SAP Concur or Navan. For remote work equipment, companies commonly offer initial onboarding stipends between $500 and $1,000, though specific renewal cycles and accounting codes depend on your company's individual human resources and procurement guidelines.
                """.trimIndent()
            }

            qLower.contains("drone") || qLower.contains("vanguard") || qLower.contains("wind") || qLower.contains("altitude") || qLower.contains("beacon") || qLower.contains("battery") -> {
                """
                Commercial drones typically have a maximum legal flight ceiling of 400 feet (approximately 120 meters) above ground level in most jurisdictions under FAA Part 107 or EASA regulations. 
                
                Standard commercial quadcopters can usually tolerate winds between 20 to 30 mph (32–48 km/h). In case of signal loss, modern drones often feature automated Return-to-Home (RTH) using GPS. Battery lifespans for high-performance LiPo batteries generally range around 200–300 charge cycles before significant capacity degradation occurs. Refer to the manufacturer user manual for model-specific emergency beacon frequencies and maintenance schedules.
                """.trimIndent()
            }

            else -> {
                """
                As a general AI model without access to your proprietary documents or internal records, I can offer general knowledge regarding your question:
                
                "$query"
                
                Standard industry practices typically recommend consulting your organization's formal policy documentation, system technical manual, or designated administrator for exact parameters, codes, and binding legal or operational requirements.
                """.trimIndent()
            }
        }
    }
}
